name: Test Action for CTF
on:
  push:
    branches:
      - main

jobs:
  request-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make HTTP Request with JSON Header
        run: |
          curl -X GET https://actions.ctf.cert.unlp.edu.ar \
          -H "Content-Type: application/json"
